pipeline:
  name: spring-ci
  identifier: springci
  projectIdentifier: cicdproject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHubconnector
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    shell: Bash
                    command: |-
                      cd SmallestSpringApp
                      mvn -B clean package
                      mvn -B test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build And Push to Docker Registry
                  identifier: Build_And_Push_to_Docker_Registry
                  spec:
                    connectorRef: DockerHubconnector
                    repo: shamamumtaz/spring-ci
                    tags:
                      - v1.0
                    dockerfile: Dockerfile
                    context: SmallestSpringApp
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: smallestspringservice
          environment:
            environmentRef: minikubedev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8sinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
