pipeline:
  name: spring-ci
  identifier: springci
  projectIdentifier: cicdproject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHubconnector
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    shell: Bash
                    command: |-
                      cd SmallestSpringApp
                      mvn -B clean package
                      mvn -B test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build And Push to Docker Registry
                  identifier: Build_And_Push_to_Docker_Registry
                  spec:
                    connectorRef: DockerHubconnector
                    repo: shamamumtaz/spring-ci
                    tags:
                      - v1.0
                    dockerfile: Dockerfile
